import {
  categoryLoader,
  classLoader,
  examLoader,
  kelasExamsLoader,
  kelasLoader,
  kelasTugasLoader,
  multipleChoiceCreateLoader,
  multipleChoiceEditLoader,
  multipleChoiceLoader,
  penilaianTugasLoader,
  shortQuizAddLoader,
  shortQuizEditLoader,
  shortQuizLoader,
  teacherClassesLoader,
  tugasAddLoader,
  tugasDetailLoader,
  tugasEditLoader,
  tugasLoader,
  tugasSubmitLoader,
  userLoader,
} from "./loaders";

export {
  categoryLoader,
  classLoader,
  examLoader,
  kelasExamsLoader,
  kelasLoader,
  kelasTugasLoader,
  multipleChoiceCreateLoader,
  multipleChoiceEditLoader,
  multipleChoiceLoader,
  penilaianTugasLoader,
  shortQuizAddLoader,
  shortQuizEditLoader,
  shortQuizLoader,
  teacherClassesLoader,
  tugasAddLoader,
  tugasDetailLoader,
  tugasEditLoader,
  tugasLoader,
  tugasSubmitLoader,
  userLoader,
};
